spring:
  application:
    name: parkmongoapi
  data:
    mongodb:
      uri: mongodb://root:pass@mongo:27017/park
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-stacktrace: never

