spring:
  application:
    name: parkmongoapi
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: javafiapgrupo29@gmail.com ${EMAIL_USERNAME}
    password: wktjmmafhonbxkjn ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-stacktrace: never

